# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb821f14c24d64fb182fd7e1c41556b93be5a796599eb8bbef0733a1385b62bc04b0f1d4ae6d0f88cdf8d60726bfde76f91eb48a941e165d1fc0524ba3c0d21f

test:
  secret_key_base: 852092ca9a2fb841da16af414d1a218773fcc5206c073094d473a59eb72b46d1dae1f4ff71726bed969330914c7e85031302378c8032de8522dd2833e0fca2f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
